### ISSUE TITLE
Occasionally internal oauth code throws can't get token error 

### ISSUE THREAD

**Issue by thisisthefuture** [thisisthefuture/whatsfordinner#1]
Need to find a consistent repro.
It seems to happen when I'm testing something fresh. Refreshing the browser works around the problem.

Issue can occationally be reproduced with a tab in Private mode.

`InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (c:\Users\alice\OneDrive\Documents\GitHub\whatsfordinner\node_modules\passport-oauth2\lib\strategy.js:379:17)
    at c:\Users\alice\OneDrive\Documents\GitHub\whatsfordinner\node_modules\passport-oauth2\lib\strategy.js:166:45
    at c:\Users\alice\OneDrive\Documents\GitHub\whatsfordinner\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (c:\Users\alice\OneDrive\Documents\GitHub\whatsfordinner\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (c:\Users\alice\OneDrive\Documents\GitHub\whatsfordinner\node_modules\oauth\lib\oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by thisisthefuture** [comment]
Hasn't reproduced in the bunch of changes and testing I've done with the latest set of checkins.

**Comment by thisisthefuture** [comment]
Happened again locally:

```App is running on port 5000
No user:	 :(
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (c:\Users\alice\OneDrive\Documents\GitHub\whatsfordinner\node_modules\passport-oauth2\lib\strategy.js:379:17)
    at c:\Users\alice\OneDrive\Documents\GitHub\whatsfordinner\node_modules\passport-oauth2\lib\strategy.js:166:45
    at c:\Users\alice\OneDrive\Documents\GitHub\whatsfordinner\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (c:\Users\alice\OneDrive\Documents\GitHub\whatsfordinner\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (c:\Users\alice\OneDrive\Documents\GitHub\whatsfordinner\node_modules\oauth\lib\oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
